# Application Environment Variables (Generated from Vault)
# Auto-generated by Vault Agent - DO NOT EDIT MANUALLY

{{ with secret "secret/app/config" }}
APP_NAME={{ .Data.data.name }}
APP_ENV={{ .Data.data.env }}
DOMAIN={{ .Data.data.domain }}
HOME_PAGE={{ .Data.data.home_page }}
NODE_ENV={{ .Data.data.node_env }}
{{ end }}

{{ with secret "secret/app/jwt" }}
JWT_SECRET={{ .Data.data.secret }}
TIME_TOKEN_EXPIRATION={{ .Data.data.expiration }}
{{ end }}

{{ with secret "secret/app/database" }}
POSTGRES_HOST={{ .Data.data.host }}
POSTGRES_PORT={{ .Data.data.port }}
POSTGRES_DB={{ .Data.data.database }}
POSTGRES_USER={{ .Data.data.username }}
POSTGRES_PASSWORD={{ .Data.data.password }}
{{ end }}

{{ with secret "secret/app/redis" }}
REDIS_HOST={{ .Data.data.host }}
REDIS_PORT={{ .Data.data.port }}
REDIS_PASSWORD={{ .Data.data.password }}
{{ end }}

{{ with secret "secret/app/oauth/github" }}
GITHUB_CLIENT_ID={{ .Data.data.client_id }}
GITHUB_CLIENT_SECRET={{ .Data.data.client_secret }}
GITHUB_CALLBACK_URL={{ .Data.data.callback_url }}
{{ end }}

{{ with secret "secret/app/oauth/intra" }}
INTRA_CLIENT_ID={{ .Data.data.client_id }}
INTRA_CLIENT_SECRET={{ .Data.data.client_secret }}
INTRA_CALLBACK_URL={{ .Data.data.callback_url }}
{{ end }}

{{ with secret "secret/app/oauth/google" }}
GOOGLE_CLIENT_ID={{ .Data.data.client_id }}
GOOGLE_CLIENT_SECRET={{ .Data.data.client_secret }}
GOOGLE_CALLBACK_URL={{ .Data.data.callback_url }}
{{ end }}

{{ with secret "secret/app/email" }}
GMAIL_APP_EMAIL={{ .Data.data.email }}
GMAIL_APP_PASSWORD={{ .Data.data.password }}
{{ end }}

{{ with secret "secret/app/rate-limit" }}
TIME_BTWN_REQUESTS={{ .Data.data.time_between_requests }}
NUMBER_OF_REQUESTS_TO_BAN={{ .Data.data.requests_to_ban }}
CLEANUP_INTERVAL={{ .Data.data.cleanup_interval }}
{{ end }}