# Logging Environment Variables (Generated from Vault)
# Autogenerated by Vault Agent  DO NOT EDIT MANUALLY

{{ with secret "secret/logging/elasticsearch" }}
ELASTIC_USERNAME={{ .Data.data.username }}
ELASTIC_PASSWORD={{ .Data.data.password }}
ELASTICSEARCH_HOST={{ .Data.data.host }}
ELASTICSEARCH_PORT={{ .Data.data.port }}
ELASTIC_CLUSTER_NAME={{ .Data.data.cluster_name }}
{{ end }}

{{ with secret "secret/logging/kibana" }}
KIBANA_HOST={{ .Data.data.host }}
KIBANA_PORT={{ .Data.data.port }}
ELASTICSEARCH_HOST_PORT={{ .Data.data.elasticsearch_url }}
{{ end }}

{{ with secret "secret/logging/logstash" }}
LOGSTASH_HOST={{ .Data.data.host }}
LOGSTASH_PORT={{ .Data.data.port }}
LOGSTASH_HEAP_SIZE={{ .Data.data.heap_size }}
{{ end }}

{{ with secret "secret/logging/config" }}
ELK_VERSION={{ .Data.data.elk_version }}
ELASTICSEARCH_HEAP={{ .Data.data.elasticsearch_heap }}
LOGSTASH_HEAP={{ .Data.data.logstash_heap }}
{{ end }}