# Monitoring Environment Variables (Generated from Vault)
# Autogenerated by Vault Agent - DO NOT EDIT MANUALLY

{{ with secret "secret/monitoring/grafana" }}
GRAFANA_USER={{ .Data.data.admin_user }}
GRAFANA_PASSWORD={{ .Data.data.admin_password }}
GRAFANA_ADMIN_PASSWORD={{ .Data.data.admin_password }}
{{ end }}

{{ with secret "secret/monitoring/prometheus" }}
PROMETHEUS_RETENTION_TIME={{ .Data.data.retention_time }}
{{ end }}

{{ with secret "secret/monitoring/config" }}
DATACENTER={{ .Data.data.datacenter }}
{{ end }}