# Module: system
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.x/filebeat-module-system.html

- module: system
  # Syslog
  syslog:
    enabled: true
    var.paths: ["/var/log/syslog*", "/var/log/messages*"]
    
  # Authorization logs
  auth:
    enabled: true
    var.paths: ["/var/log/auth.log*", "/var/log/secure*"]


