tls:
  certificates:
    - certFile: /etc/ssl/certs/regex-33.crt
      keyFile: /etc/ssl/certs/regex-33.key
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/certs/regex-33.crt
        keyFile: /etc/ssl/certs/regex-33.key
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

