version: '3.8'

services:
  # Private Docker Registry
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - registry-network
    configs:
      - source: registry-config-file
        target: /etc/docker/registry/config.yml
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Registry UI (Optional - for web interface)
  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "5002:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 8s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.registry-ui.rule=Host(`registry-ui.regex-33.com`)"
        - "traefik.http.routers.registry-ui.entrypoints=web,websecure"
        - "traefik.http.routers.registry-ui.tls=true"
        - "traefik.http.services.registry-ui.loadbalancer.server.port=80"
        - "traefik.http.routers.registry-ui.middlewares=registry-ui-auth@file,security-headers@file"
        # Replace these with your generated hashes
        - "traefik.docker.network=traefik-public"
    networks:
      - registry-network
      - traefik-public
    environment:
      REGISTRY_TITLE: "FT Transcendence Private Registry"
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      SINGLE_REGISTRY: "true"
    depends_on:
      - registry
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
# Network Definitions
networks:
  registry-network:
    external: true
  traefik-public:
    external: true

# Volume Definitions
volumes:
  registry-data:
    driver: local

# Configs Definitions
configs:
  registry-config-file:
    external: true