global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ft-transcendence'

rule_files:
  - "/etc/prometheus/rules/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Docker Swarm services discovery
  - job_name: 'docker-swarm-services'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: services
        port: 9323
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: service_name
      - source_labels: [__meta_dockerswarm_service_label_com_docker_stack_namespace]
        target_label: stack_name

  # Docker Swarm nodes discovery
  - job_name: 'docker-swarm-nodes'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
        port: 9100
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: node_name
      - source_labels: [__meta_dockerswarm_node_role]
        target_label: node_role

  # Infrastructure services
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node-exporter-manager:9100'
          - 'node-exporter-logging:9100'
          - 'node-exporter-monitoring:9100'
    scrape_interval: 10s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor-manager:8080'
          - 'cadvisor-logging:8080'
          - 'cadvisor-monitoring:8080'
    scrape_interval: 10s
    metrics_path: '/metrics'


  # elasticsearch-exporter
  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    metrics_path: '/metrics'
    scrape_interval: 15s

